### ISSUE TITLE
Sample show GetDroidModel.DeviceHardware.Model but should end in GetModel

### ISSUE THREAD

**Issue by raymondjstone** [dannycabrera/GetDroidModel#1]

**Comment by dannycabrera** [comment]
Thank you for letting me know @raymondjstone will get the readme samples corrected today.

**Comment by raymondjstone** [comment]
Was not the readme samples I was referring to but the text on

**Comment by raymondjstone** [comment]
In the meantime thanks for this and especially the IOS version.

**Comment by dannycabrera** [comment]
No problem, glad it's helpful. Just updated ReadMe and thanks once again for letting me know.
